---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - capy-controller.Application.yaml
  - ../config/manager/
#  - resources/
#  - extra-resources/

patches:
  - path: patches/capy-controller-manager.Deployment.yaml
