// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yandex-cloud/cluster-api-provider-yandex/internal/pkg/client (interfaces: YandexClientGetter)
//
// Generated by this command:
//
//	mockgen -build_flags=--mod=mod -package mock_client -destination=mock_client/identity.go . YandexClientGetter
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	reflect "reflect"

	client "github.com/yandex-cloud/cluster-api-provider-yandex/internal/pkg/client"
	gomock "go.uber.org/mock/gomock"
	client0 "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockYandexClientGetter is a mock of YandexClientGetter interface.
type MockYandexClientGetter struct {
	ctrl     *gomock.Controller
	recorder *MockYandexClientGetterMockRecorder
}

// MockYandexClientGetterMockRecorder is the mock recorder for MockYandexClientGetter.
type MockYandexClientGetterMockRecorder struct {
	mock *MockYandexClientGetter
}

// NewMockYandexClientGetter creates a new mock instance.
func NewMockYandexClientGetter(ctrl *gomock.Controller) *MockYandexClientGetter {
	mock := &MockYandexClientGetter{ctrl: ctrl}
	mock.recorder = &MockYandexClientGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockYandexClientGetter) EXPECT() *MockYandexClientGetterMockRecorder {
	return m.recorder
}

// GetDefault mocks base method.
func (m *MockYandexClientGetter) GetDefault(arg0 context.Context) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefault", arg0)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefault indicates an expected call of GetDefault.
func (mr *MockYandexClientGetterMockRecorder) GetDefault(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefault", reflect.TypeOf((*MockYandexClientGetter)(nil).GetDefault), arg0)
}

// GetFromKey mocks base method.
func (m *MockYandexClientGetter) GetFromKey(arg0 context.Context, arg1 string) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromKey", arg0, arg1)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromKey indicates an expected call of GetFromKey.
func (mr *MockYandexClientGetterMockRecorder) GetFromKey(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromKey", reflect.TypeOf((*MockYandexClientGetter)(nil).GetFromKey), arg0, arg1)
}

// GetFromSecret mocks base method.
func (m *MockYandexClientGetter) GetFromSecret(arg0 context.Context, arg1 client0.Client, arg2, arg3, arg4 string) (client.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFromSecret", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(client.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFromSecret indicates an expected call of GetFromSecret.
func (mr *MockYandexClientGetterMockRecorder) GetFromSecret(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFromSecret", reflect.TypeOf((*MockYandexClientGetter)(nil).GetFromSecret), arg0, arg1, arg2, arg3, arg4)
}
